apps/blog/urls.py
from django.urls import path
from .views import blogView

app_name = 'blog'

urlpatterns = [
    path('', blogView, name='blog'),
]

apps/honey/urls.py
from django.urls import path
from .views import transactionsView

app_name = 'honey'

urlpatterns = [
    path('', transactionsView, name='transactions'),
]

apps/hossaik/urls.py
from django.urls import path
from .views import hossaikView

app_name = 'hossaik'

urlpatterns = [
    path('', hossaikView, name='index'),
]

apps/users/urls.py
from django.urls import path
from .views import loginView

app_name = 'users'

urlpatterns = [
    path('', loginView, name='login'),
]

hossaik/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.hossaik.urls')),
    path('honey/', include('apps.honey.urls')),
    path('users/', include('apps.users.urls')),
    path('blog/', include('apps.blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/blog/models.py
from django.db import models

# Create your models here.

apps/honey/models.py
from django.db import models

# Create your models here.

apps/hossaik/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models

# Create your models here.

apps/blog/views.py
from django.shortcuts import render

# Create your views here.


def blogView(request):
    context = {
        'title': 'Blog'
    }
    return render(request, 'blog/home.html', context)

apps/honey/views.py
from django.shortcuts import render

# Create your views here.

def transactionsView(request):
    context = {
        'title': 'Transactions'
    }
    return render(request, 'honey/transactions.html', context)

apps/hossaik/views.py
from django.shortcuts import render


def hossaikView(request):
    context = {
        'title': 'Hossaik'
    }
    return render(request, 'hossaik/index.html', context)

apps/users/views.py
from django.shortcuts import render

# Create your views here.


def loginView(request):
    context = {
        'title': 'Login'
    }
    return render(request, 'users/login.html', context)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        {% comment %} CSS {% endcomment %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!-- Bootstrap CSS v5.2.1 -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>

    <body>
        <header>
            {% include "./includes/navbar.html" %}
        </header>

        <main class="container m-5">

            {% block content  %}

            {% endblock  %}

        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        {% comment %} JS {% endcomment %}
        <script src="{% static 'js/app.js' %}"></script>
        <!-- Bootstrap JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>   
    </body>
</html>

templates/blog/home.html
{% extends '../base.html' %}


{% block content %}

    <h2>Welcome to my blog</h2>

{% endblock  %}

templates/honey/transactions.html
{% extends '../base.html' %}


{% block content %}

    <h2>Welcome to Transactions</h2>

{% endblock  %}

templates/hossaik/index.html
{% extends '../base.html' %}


{% block content %}

    <h2>Welcome to hossaik</h2>

{% endblock  %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark ps-3  ">
  <a class="navbar-brand" href="{% url "hossaik:index" %}">Hossaik</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "hossaik:index" %}">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "blog:blog" %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "honey:transactions" %}">Honey</a>
      </li>
    </ul>

    <ul class="navbar-nav ms-auto pe-5">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "users:login" %}">Login</a>
      </li>
    </ul>
    
  </div>
</nav>

templates/users/login.html
{% extends '../base.html' %}


{% block content %}

    <div class=" row">
        <div class="mx-auto col-md-12 col-lg-6 formContainer">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" aria-describedby="usernameHelp" placeholder="Enter username">
                    <small id="usernameHelp" class="form-text text-muted">We'll never share your information with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="Password1">Password</label>
                    <input type="password" class="form-control" id="Password1" placeholder="Password">
                </div>
        
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>

{% endblock  %}